### ISSUE TITLE
 Automatically Save iSeg Output

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-issues#665]
Accoring to @mguidon from #620 :

```
The saving is a bit more convoluted but we have the exact same problem with sim4lfe and the jupyterlabs. This would require a change in the iSeg code base to enable some sort of API that enables the system to tell the application to save the current project. Now, even if we can do that, would you always just store the current project? Would you just create a backup? Would you have the user to answer this question for every dynamic service in a study?
```

@newton1985 comments:
```
after thinking this over another time, the easiest solution is probably just to automatically pull up the outputs/output_1 (or outputs/output_2 if outputs_1 has data etc) directory every time the user clicks "save". since the service is interactive anyway, we probably don't need to obsess over eliminating interactive steps (i.e. fully automated saving). it's more about avoiding the navigation of the filesystem.
```

**Comment by newton1985** [comment]
@mguidon @mrnicegyu11 - I think that automatically pulling up outputs/output_1 in the filesystem dialog box when a user clicks "Save Project" is a perfectly fine solution.

**Comment by elisabettai** [comment]
Hi @mguidon, this is resolved right? I think you presented that at the Vaporwave review meeting (Oct 7)

**Comment by mguidon** [comment]
Awaiting feedback from @newton1985

**Comment by mguidon** [comment]
- Save As opens in `/home/scu/work/outputs/output_1`
- Open opens in `/home/scu/work/inputs/input_1`

**Comment by sanderegg** [comment]
any comment on that one @newton1985 ? is this still an issue?

**Comment by newton1985** [comment]
@sanderegg thanks for following up! As far as I can tell it is still an issue.
